name 'poise-web'
maintainer 'Luis De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'Installs/Configures web things'
long_description 'Installs/Configures web things'
version '0.0.1'

depends 'poise'
depends 'poise-service'
depends 'build-essential'
depends 'poise-s3'
depends 'poise-fpm'
